# Suggest a new feature or improvement for a project.
name: "✨ Feature Request"
description: Suggest a new feature or improvement for this project
title: "[Feature] <short description>"
labels:
  - feature-request
  - enhancement
  - feature
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thank you for taking the time to suggest a new feature or improvement!

  - type: dropdown
    id: subcategory
    attributes:
      label: Subcategory
      description: Select the type of feature request. If none apply, select "_No Response_".
      options:
        - new-feature - Entirely new functionality
        - feature-enhancement - Improving existing features
        - ui-ux-improvement - Workflow or design enhancement
        - accessibility-request - a11y features for users with disabilities
        - integration-request - Suggesting 3rd-party tool or API integration
        - configurability - Suggesting more options/settings
        - _No Response_
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the feature or improvement you are requesting. If not applicable, write "_No Response_".
      placeholder: What problem does this solve? What would you like to see? If not applicable, type "_No Response_".
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? Who would benefit from it?
      placeholder: Explain the motivation behind this request.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternatives or workarounds?
      placeholder: List any alternatives you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: Any other information?
    validations:
      required: false