name: Code Quality

on:
  push:
    paths:
      - 'mpesa_sdk/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/code-quality.yml'
  pull_request:
    paths:
      - 'mpesa_sdk/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/code-quality.yml'

jobs:
  ruff-lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '3.13'

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install project & dev dependencies
        run: uv pip install -e '.[dev]'

      - name: Ruff Lint
        run: uv run ruff check mpesa_sdk

      - name: Ruff Format Check
        run: uv run ruff format --check mpesa_sdk

  mypy-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '3.13'
      
      - name: Create virtual environment
        run: uv venv .venv

      - name: Install project & dev dependencies
        run: uv pip install -e '.[dev]'

      - name: Run Mypy (Type Checking)
        run: uv run mypy mpesa_sdk

  bandit-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '3.13'
      
      - name: Create virtual environment
        run: uv venv .venv

      - name: Install Bandit and project
        run: |
          uv pip install -e .
          uv pip install bandit

      - name: Run Bandit Security Check
        run: uv run bandit -r mpesa_sdk