name: Code Quality

on:
  push:
    paths:
      - 'mpesa_sdk/**/*.py'
      - '.github/workflows/code-quality.yml'
  pull_request:
    paths:
      - 'mpesa_sdk/**/*.py'
      - '.github/workflows/code-quality.yml'

jobs:
  ruff-lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff Lint
        run: ruff check mpesa_sdk

      - name: Ruff Format Check
        run: ruff format --check mpesa_sdk

  mypy-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Mypy
        run: pip install mypy types-requests pydantic

      - name: Run Mypy (Type Checking)
        run: mypy mpesa_sdk
    
  bandit-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Check
        run: bandit -r mpesa_sdk