name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install ".[dev,test]"
            pip install pytest
            pip install -e .

      - name: Run unit tests
        run: |
          pytest tests/unit